# Generated by Django 4.0.6 on 2022-07-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=800)),
                ('rating', models.IntegerField()),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]
